export { default as RedesFooter} from "./BoxFooter/BoxRedes"
export { default as BoxTL} from "./BoxFooter/BoxTL"
export { default as AboutBox} from "./BoxFooter/BoxAbout"
export { default as BoxDevelopers } from "./BoxFooter/BoxDevelpors"
export { default as BoxCopyright } from "./BoxFooter/BoxCopyright"
export { default as BoxContactFooter } from "./BoxFooter/BoxContacto"